-- ========================================
--- SECUENCIA IDENTIFICADORES PRINCIPALES
-- ========================================

-- 1 CARGO
CREATE SEQUENCE seq_id_cargo
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- 2 PSICOLOGO
CREATE SEQUENCE seq_id_psicologo
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 3 FACULTAD
CREATE SEQUENCE seq_id_facultad
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 4 CARRERA
CREATE SEQUENCE seq_id_carrera
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 5 PACIENTE
CREATE SEQUENCE seq_id_paciente
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 6 DOCENTE
CREATE SEQUENCE seq_id_docente
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 7 ADMINISTRATIVO
CREATE SEQUENCE seq_id_administrativo
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 8 SERVICIO
CREATE SEQUENCE seq_id_servicio
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 9 CITA
CREATE SEQUENCE seq_id_cita
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
