-- ========================================
-- SECUENCIAS IDENTIFICADORES PRINCIPALES
-- ========================================

-- 1 CARGO
CREATE SEQUENCE seq_id_cargo
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- 2 PSICOLOGO
CREATE SEQUENCE seq_id_psicologo
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 3 FACULTAD
CREATE SEQUENCE seq_id_facultad
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 4 CARRERA
CREATE SEQUENCE seq_id_carrera
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 5 PACIENTE / ESTUDIANTE
CREATE SEQUENCE seq_id_paciente
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 6 DOCENTE
CREATE SEQUENCE seq_id_docente
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 7 ADMINISTRATIVO
CREATE SEQUENCE seq_id_administrativo
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 8 SERVICIO
CREATE SEQUENCE seq_id_servicio
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 9 CITA
CREATE SEQUENCE seq_id_cita
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 10 TIPO TELEFONO ESTUDIANTE
CREATE SEQUENCE seq_id_tipo_tlf_est
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 11 TIPO TELEFONO DOCENTE
CREATE SEQUENCE seq_id_tipo_tlf_doc
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 12 TIPO TELEFONO ADMINISTRATIVO
CREATE SEQUENCE seq_id_tipo_tlf_admin
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 13 AUDITORIA
CREATE SEQUENCE seq_auditoria
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 14 REPORTE ATENCIONES
CREATE SEQUENCE seq_id_reporte
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

